# Generated by Django 5.2.1 on 2025-05-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('std', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=15)),
            ],
        ),
    ]
